"use client";

import { useEffect, useMemo, useState } from "react";
import "./agendamento.css";
import { createClient } from "@/lib/supabase";

type Step = "date" | "time" | "barber" | "service" | "summary";
const steps: Step[] = ["date", "time", "barber", "service", "summary"];
const stepTitle: Record<Step, string> = { date:"Escolha a data", time:"Escolha o horário", barber:"Escolha o barbeiro", service:"Escolha os serviços", summary:"Resumo do agendamento" };
const timeSlots = ["08:00","08:30","09:00","09:30","10:00","10:30","11:00","11:30","13:00","13:30","14:00","14:30","15:00","15:30","16:00","16:30","17:00","17:30","18:00","18:30"];
const monthNames = ["Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"];
function toDateKey(date: Date) { return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`; }
function formatDate(value: string) { if (!value) return ""; const [y,m,d] = value.split("-").map(Number); return new Date(y,m-1,d).toLocaleDateString("pt-BR", { weekday:"long", day:"2-digit", month:"long", year:"numeric" }); }
function formatTime(value: string) { return value.slice(0,5); }

export default function ClientBookingPage() {
  const [barbershopId, setBarbershopId] = useState("");
  const [barbershopName, setBarbershopName] = useState("Sua Barbearia");
  const [step, setStep] = useState<Step>("date");
  const [month, setMonth] = useState(() => { const now = new Date(); return new Date(now.getFullYear(), now.getMonth(), 1); });
  const [date, setDate] = useState(""); const [time, setTime] = useState(""); const [barber, setBarber] = useState(""); const [services, setServices] = useState<string[]>([]);
  const [serviceInput, setServiceInput] = useState(""); const [clientName, setClientName] = useState(""); const [clientWhatsapp, setClientWhatsapp] = useState(""); const [confirmed, setConfirmed] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState("");

  useEffect(() => { const params = new URLSearchParams(window.location.search); const id = params.get("barbershop") || ""; setBarbershopId(id); const passedName = params.get("nome"); if (passedName) setBarbershopName(passedName); if (!id) { setError("Não foi possível identificar a barbearia."); return; } const supabase = createClient(); (async () => { const { data } = await supabase.from("barbershops").select("name").eq("id", id).maybeSingle(); if (data?.name) setBarbershopName(data.name); })(); }, []);
  const today = useMemo(() => { const d = new Date(); d.setHours(0,0,0,0); return d; }, []);
  const calendar = useMemo(() => { const first = new Date(month.getFullYear(), month.getMonth(), 1); const last = new Date(month.getFullYear(), month.getMonth()+1, 0); const cells: Date[] = []; for (let i=0; i<first.getDay(); i++) cells.push(new Date(month.getFullYear(), month.getMonth(), 1-i)); for (let d=1; d<=last.getDate(); d++) cells.push(new Date(month.getFullYear(), month.getMonth(), d)); while (cells.length % 7) cells.push(new Date(month.getFullYear(), month.getMonth()+1, cells.length-cells.length%7+1)); return cells; }, [month]);
  const next = () => { setError(""); if (step === "date" && date) setStep("time"); else if (step === "time" && time) setStep("barber"); else if (step === "barber" && barber.trim()) setStep("service"); else if (step === "service" && services.length) setStep("summary"); };
  const back = () => { const i = steps.indexOf(step); if (i > 0) setStep(steps[i-1]); };
  const addService = () => { const value = serviceInput.trim(); if (!value || services.includes(value)) return; setServices((current) => [...current, value]); setServiceInput(""); };
  const removeService = (service: string) => setServices((current) => current.filter((item) => item !== service));
  const confirmBooking = async () => { if (!barbershopId) { setError("Não foi possível identificar a barbearia."); return; } if (!clientName.trim() || !clientWhatsapp.trim()) { setError("Informe seu nome e WhatsApp."); return; } if (!barber.trim() || !services.length) { setError("Informe o barbeiro e pelo menos um serviço."); return; } setSaving(true); setError(""); const { error: insertError } = await createClient().from("appointments").insert({ barbershop_id: barbershopId, appointment_date: date, appointment_time: time, barber_name: barber.trim(), services, client_name: clientName.trim(), client_whatsapp: clientWhatsapp.trim() }); if (insertError) { setError("Não foi possível concluir o agendamento. Tente novamente."); setSaving(false); return; } setSaving(false); setConfirmed(true); window.setTimeout(() => restart(), 1200); };
  const restart = () => { setStep("date"); setDate(""); setTime(""); setBarber(""); setServices([]); setServiceInput(""); setClientName(""); setClientWhatsapp(""); setConfirmed(false); setError(""); };

  return <main className="booking-shell"><header className="booking-header"><div className="booking-brand">Barba<span>10</span></div><div className="booking-shop-name">{barbershopName}</div></header><section className="booking-content"><div className="booking-progress">{steps.map((item, i) => <span key={item} className={steps.indexOf(step) >= i ? "done" : ""} />)}</div><div className="booking-card"><span className="booking-kicker">AGENDAMENTO</span><h1>{confirmed ? "Agendamento confirmado" : stepTitle[step]}</h1><p className="booking-subtitle">{confirmed ? "Seu agendamento foi registrado. Voltando ao calendário..." : "Agende seu atendimento de forma rápida e segura."}</p>
    {!confirmed && step === "date" && <div className="calendar"><div className="calendar-nav"><button type="button" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth()-1, 1))} disabled={month <= new Date(today.getFullYear(), today.getMonth(), 1)}>‹</button><strong>{monthNames[month.getMonth()]} {month.getFullYear()}</strong><button type="button" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth()+1, 1))}>›</button></div><div className="weekdays">{["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"].map((d) => <span key={d}>{d}</span>)}</div><div className="calendar-grid">{calendar.map((d, i) => { const currentMonth = d.getMonth() === month.getMonth(); const past = d < today; const key = toDateKey(d); return <button key={`${key}-${i}`} type="button" disabled={!currentMonth || past} className={`${date === key ? "selected " : ""}${!currentMonth ? "muted " : ""}`} onClick={() => setDate(key)}>{d.getDate()}</button>; })}</div></div>}
    {!confirmed && step === "time" && <div className="choice-grid">{timeSlots.map((item) => <button key={item} type="button" className={time === item ? "selected" : ""} onClick={() => setTime(item)}>{item}</button>)}</div>}
    {!confirmed && step === "barber" && <div className="field-stack"><label>Nome do barbeiro<input value={barber} onChange={(e) => setBarber(e.target.value)} placeholder="Digite o nome do barbeiro" /></label><p className="field-note">O barbeiro escolhido será registrado neste agendamento.</p></div>}
    {!confirmed && step === "service" && <div className="field-stack"><div className="service-entry"><label>Serviço<input value={serviceInput} onChange={(e) => setServiceInput(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); addService(); } }} placeholder="Ex.: Corte" /></label><button type="button" onClick={addService}>Adicionar</button></div>{services.length > 0 && <div className="service-tags">{services.map((service) => <button type="button" key={service} onClick={() => removeService(service)}>{service} ×</button>)}</div>}<p className="field-note">Você pode adicionar mais de um serviço ao mesmo agendamento.</p></div>}
    {!confirmed && step === "summary" && <div className="summary"><div><span>Barbearia</span><strong>{barbershopName}</strong></div><div><span>Data</span><strong>{formatDate(date)}</strong></div><div><span>Horário</span><strong>{formatTime(time)}</strong></div><div><span>Barbeiro</span><strong>{barber}</strong></div><div><span>Serviços</span><strong>{services.join(", ")}</strong></div><div className="client-fields"><label>Nome<input value={clientName} onChange={(e) => setClientName(e.target.value)} placeholder="Seu nome" /></label><label>WhatsApp<input value={clientWhatsapp} onChange={(e) => setClientWhatsapp(e.target.value)} placeholder="(00) 00000-0000" inputMode="tel" /></label></div><button className="confirm" type="button" onClick={confirmBooking} disabled={saving}>{saving ? "Salvando..." : "Confirmar agendamento"}</button></div>}
    {error && <div className="booking-error" role="alert">{error}</div>}{!confirmed && <div className="booking-actions">{step !== "date" && <button className="secondary" type="button" onClick={back}>Voltar</button>}{step !== "summary" && <button className="primary" type="button" onClick={next} disabled={(step === "date" && !date) || (step === "time" && !time) || (step === "barber" && !barber.trim()) || (step === "service" && !services.length)}>Continuar</button>}</div>}</div></section></main>;
}
