"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase";
import "../login/cliente.css";

type Appointment={id:string;appointment_date:string;appointment_time:string;barber_name:string;services:string[];status:string};
function formatDate(v:string){const [y,m,d]=v.split("-").map(Number);return new Date(y,m-1,d).toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit",year:"numeric"})}
function isHistory(a:Appointment){const dt=new Date(`${a.appointment_date}T${a.appointment_time}`);return dt<new Date()||['cancelled','canceled','completed'].includes((a.status||'').toLowerCase())}
export default function HistoricoCliente(){const router=useRouter();const [items,setItems]=useState<Appointment[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");useEffect(()=>{(async()=>{const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/cliente/login");return}const {data,error:e}=await supabase.from("appointments").select("id,appointment_date,appointment_time,barber_name,services,status").eq("client_id",user.id).order("appointment_date",{ascending:false}).order("appointment_time",{ascending:false});if(e){setError("Não foi possível carregar seu histórico.");setLoading(false);return}setItems((data||[]) as Appointment[]);setLoading(false)})()},[router]);const history=items.filter(isHistory);return <main className="customer-shell"><header className="customer-header"><div className="customer-brand">Barba<span>10</span></div><div className="customer-shop">Histórico</div></header><section className="customer-content"><div className="customer-card"><span className="customer-kicker">ÁREA DO CLIENTE</span><h1>Histórico</h1><p>Seus atendimentos anteriores.</p>{loading?<div className="customer-message">Carregando...</div>:error?<div className="customer-error">{error}</div>:history.length===0?<div className="customer-message">Ainda não há atendimentos no seu histórico.</div>:<div style={{display:"grid",gap:10}}>{history.map(a=><div key={a.id} style={{padding:15,border:"1px solid #29292d",borderRadius:13,background:"#19191d"}}><strong>{formatDate(a.appointment_date)} às {a.appointment_time.slice(0,5)}</strong><p style={{margin:"8px 0 0",color:"#aaa"}}>{a.barber_name} • {(a.services||[]).join(", ")}</p><small style={{color:"#777"}}>Status: {a.status||"registrado"}</small></div>)}</div>}<button className="customer-back" onClick={()=>router.push("/agendamento")}>Voltar para agendamento</button></div></section></main>}
