"use client";
import { FormEvent, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase";
import "./cliente.css";
type Draft={barbershopId:string;barbershopName:string;date:string;time:string;barberId:string;barberName:string;services:string[];serviceNames:string[];clientName:string;clientWhatsapp:string};
function normalize(value:string){return value.replace(/\D/g,"")}
export default function CustomerLoginPage(){
 const params=typeof window!=="undefined"?new URLSearchParams(window.location.search):null;const barbershopId=params?.get("barbershop")||"";const barbershopName=params?.get("nome")||"Sua Barbearia";
 const [mode,setMode]=useState<"login"|"signup">("login");const [identifier,setIdentifier]=useState("");const [name,setName]=useState("");const [whatsapp,setWhatsapp]=useState("");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [passwordConfirm,setPasswordConfirm]=useState("");const [loading,setLoading]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");const [pending,setPending]=useState<Draft|null>(null);
 useEffect(()=>{try{const raw=sessionStorage.getItem("barba10_pending_booking");if(raw)setPending(JSON.parse(raw) as Draft)}catch{}},[]);
 useEffect(()=>{if(!pending)return;setName(pending.clientName||"");setWhatsapp(pending.clientWhatsapp||"")},[pending]);
 async function finishBooking(draft:Draft){const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Faça login para concluir o agendamento.");const {data:profile}=await supabase.from("customer_profiles").select("name,whatsapp").eq("id",user.id).maybeSingle();const finalName=profile?.name||draft.clientName.trim();const finalWhatsapp=profile?.whatsapp||draft.clientWhatsapp.trim();const {error:e}=await supabase.from("appointments").insert({barbershop_id:draft.barbershopId,client_id:user.id,barber_id:draft.barberId,appointment_date:draft.date,appointment_time:draft.time,barber_name:draft.barberName,service_ids:draft.services,services:draft.serviceNames,client_name:finalName,client_whatsapp:finalWhatsapp});if(e)throw e;sessionStorage.setItem("barba10_last_booking",JSON.stringify({...draft,clientName:finalName,clientWhatsapp:finalWhatsapp}));sessionStorage.removeItem("barba10_pending_booking");window.location.href="/cliente/confirmado"}
 async function handleLogin(e:FormEvent){e.preventDefault();setLoading(true);setError("");setMessage("");try{const supabase=createClient();let loginEmail=identifier.trim();if(!identifier.includes("@")){const {data,error:lookupError}=await supabase.rpc("customer_email_for_login",{identifier:identifier.trim()});if(lookupError||!data)throw new Error("WhatsApp ou email não encontrado.");loginEmail=data}const {error:e}=await supabase.auth.signInWithPassword({email:loginEmail,password});if(e)throw e;const raw=sessionStorage.getItem("barba10_pending_booking");if(raw)await finishBooking(JSON.parse(raw) as Draft);else window.location.href=`/agendamento?barbershop=${encodeURIComponent(barbershopId)}&nome=${encodeURIComponent(barbershopName)}`}catch(err){setError(err instanceof Error?err.message:"Não foi possível entrar. Confira seus dados.");setLoading(false)}}
 async function handleSignup(e:FormEvent){e.preventDefault();setLoading(true);setError("");setMessage("");if(!name.trim()){setError("Informe seu nome.");setLoading(false);return}if(password.length<6){setError("A senha deve ter pelo menos 6 caracteres.");setLoading(false);return}if(password!==passwordConfirm){setError("As senhas não conferem.");setLoading(false);return}if(normalize(whatsapp).length<10){setError("Informe um WhatsApp válido.");setLoading(false);return}try{const supabase=createClient();const {data,error:e}=await supabase.auth.signUp({email:email.trim().toLowerCase(),password,options:{data:{account_type:"customer",name:name.trim(),whatsapp:whatsapp.trim()},emailRedirectTo:`${window.location.origin}/cliente/login?barbershop=${encodeURIComponent(barbershopId)}&nome=${encodeURIComponent(barbershopName)}`}});if(e)throw e;if(!data.session){setMessage("Cadastro realizado. Verifique seu email para ativar a conta. Depois, volte ao Barba10 para concluir o agendamento.");setLoading(false);return}const raw=sessionStorage.getItem("barba10_pending_booking");if(raw)await finishBooking(JSON.parse(raw) as Draft);else window.location.href=`/agendamento?barbershop=${encodeURIComponent(barbershopId)}&nome=${encodeURIComponent(barbershopName)}`}catch(err){setError(err instanceof Error?err.message:"Não foi possível criar sua conta.");setLoading(false)}}
 useEffect(()=>{(async()=>{if(!pending)return;const {data:{user}}=await createClient().auth.getUser();if(!user||loading)return;try{setLoading(true);await finishBooking(pending)}catch(err){setError(err instanceof Error?err.message:"Não foi possível concluir o agendamento.");setLoading(false)}})()},[pending]);
 return <main className="customer-shell"><header className="customer-header"><div className="customer-brand">Barba<span>10</span></div><div className="customer-shop">{barbershopName}</div></header><section className="customer-content"><div className="customer-card"><span className="customer-kicker">ÁREA DO CLIENTE</span><h1>{mode==="login"?"Entrar":"Criar conta"}</h1><p>{mode==="login"?"Acesse sua conta para confirmar e acompanhar seus agendamentos.":"Cadastre seus dados para agendar com segurança."}</p>{mode==="login"?<form onSubmit={handleLogin}><label>WhatsApp ou email<input value={identifier} onChange={e=>setIdentifier(e.target.value)} placeholder="WhatsApp ou seu@email.com" autoComplete="username" required/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Sua senha" autoComplete="current-password" required/></label><button className="customer-primary" disabled={loading}>{loading?"Entrando...":"Entrar"}</button></form>:<form onSubmit={handleSignup}><label>Nome<input value={name} onChange={e=>setName(e.target.value)} placeholder="Seu nome completo" autoComplete="name" required/></label><label>WhatsApp<input value={whatsapp} onChange={e=>setWhatsapp(e.target.value)} placeholder="(00) 00000-0000" inputMode="tel" autoComplete="tel" required/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="seu@email.com" autoComplete="email" required/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mínimo de 6 caracteres" autoComplete="new-password" required/></label><label>Configuração de senha<input type="password" value={passwordConfirm} onChange={e=>setPasswordConfirm(e.target.value)} placeholder="Digite a senha novamente" autoComplete="new-password" required/></label><button className="customer-primary" disabled={loading}>{loading?"Criando conta...":"Criar conta"}</button></form>}{error&&<div className="customer-error" role="alert">{error}</div>}{message&&<div className="customer-message">{message}</div>}<div className="customer-switch">{mode==="login"?<>Ainda não tem cadastro? <button type="button" onClick={()=>{setMode("signup");setError("");setMessage("")}}>Criar conta</button></>:<>Já tem uma conta? <button type="button" onClick={()=>{setMode("login");setError("");setMessage("")}}>Entrar</button></>}</div><button className="customer-back" type="button" onClick={()=>window.history.length>1?window.history.back():window.location.href=`/agendamento?barbershop=${encodeURIComponent(barbershopId)}&nome=${encodeURIComponent(barbershopName)}`}>Voltar ao agendamento</button></div></section></main>;
}
