"use client";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase";

type ShopHour={id?:string;day_of_week:number;open_time:string;close_time:string;break_start:string;break_end:string;active:boolean};
type Barber={id:string;name:string};
type BarberHour={id?:string;barber_id:string;day_of_week:number;start_time:string;end_time:string;active:boolean};
const days=["Domingo","Segunda-feira","Terça-feira","Quarta-feira","Quinta-feira","Sexta-feira","Sábado"];
const emptyShop=(day:number):ShopHour=>({day_of_week:day,open_time:"08:00",close_time:"18:00",break_start:"12:00",break_end:"13:00",active:false});
const emptyBarber=(barber_id:string,day:number):BarberHour=>({barber_id,day_of_week:day,start_time:"08:00",end_time:"18:00",active:false});
export default function HorariosPanel({barbershopId}:{barbershopId:string}){
 const [shopHours,setShopHours]=useState<ShopHour[]>(days.map((_,i)=>emptyShop(i))); const [barbers,setBarbers]=useState<Barber[]>([]); const [selectedBarber,setSelectedBarber]=useState(""); const [barberHours,setBarberHours]=useState<BarberHour[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");const s=createClient();const [sh,br]=await Promise.all([s.from("barbershop_hours").select("id,day_of_week,open_time,close_time,break_start,break_end,active").eq("barbershop_id",barbershopId).order("day_of_week"),s.from("barbers").select("id,name").eq("barbershop_id",barbershopId).eq("active",true).order("created_at")]);if(sh.error||br.error){setError("Não foi possível carregar os horários.");setLoading(false);return}const rows=days.map((_,i)=>{const r=(sh.data??[]).find(x=>x.day_of_week===i) as ShopHour|undefined;return r?{...r,break_start:r.break_start?.slice(0,5)||"",break_end:r.break_end?.slice(0,5)||"",open_time:r.open_time.slice(0,5),close_time:r.close_time.slice(0,5)}:emptyShop(i)});setShopHours(rows);setBarbers((br.data??[]) as Barber[]);setSelectedBarber(current=>current||((br.data??[])[0]?.id||""));setLoading(false)};
 useEffect(()=>{load()},[barbershopId]);
 useEffect(()=>{if(!selectedBarber)return;let mounted=true;(async()=>{const {data,error:e}=await createClient().from("barber_hours").select("id,barber_id,day_of_week,start_time,end_time,active").eq("barber_id",selectedBarber).eq("barbershop_id",barbershopId).order("day_of_week");if(!mounted)return;if(e){setError("Não foi possível carregar a disponibilidade do barbeiro.");return}setBarberHours(days.map((_,i)=>{const r=(data??[]).find(x=>x.day_of_week===i) as BarberHour|undefined;return r?{...r,start_time:r.start_time.slice(0,5),end_time:r.end_time.slice(0,5)}:emptyBarber(selectedBarber,i)}))})();return()=>{mounted=false}},[selectedBarber,barbershopId]);
 const updateShop=(i:number,k:keyof ShopHour,v:string|boolean)=>setShopHours(a=>a.map((r,n)=>n===i?{...r,[k]:v}:r));
 const updateBarber=(i:number,k:keyof BarberHour,v:string|boolean)=>setBarberHours(a=>a.map((r,n)=>n===i?{...r,[k]:v}:r));
 const saveShop=async()=>{setSaving(true);setMessage("");setError("");const s=createClient();for(const r of shopHours){const payload={barbershop_id:barbershopId,day_of_week:r.day_of_week,open_time:r.open_time,close_time:r.close_time,break_start:r.active?r.break_start||null:null,break_end:r.active?r.break_end||null:null,active:r.active};const q=r.id?s.from("barbershop_hours").update(payload).eq("id",r.id):s.from("barbershop_hours").insert(payload);const {error:e}=await q;if(e){setError(`Não foi possível salvar ${days[r.day_of_week]}. Verifique os horários.`);setSaving(false);return}}setMessage("Horário de funcionamento salvo.");setSaving(false);await load()};
 const saveBarber=async()=>{if(!selectedBarber)return;setSaving(true);setMessage("");setError("");const s=createClient();for(const r of barberHours){const payload={barber_id:selectedBarber,barbershop_id:barbershopId,day_of_week:r.day_of_week,start_time:r.start_time,end_time:r.end_time,active:r.active};const q=r.id?s.from("barber_hours").update(payload).eq("id",r.id):s.from("barber_hours").insert(payload);const {error:e}=await q;if(e){setError(`Não foi possível salvar ${days[r.day_of_week]}.`);setSaving(false);return}}setMessage("Disponibilidade do barbeiro salva.");setSaving(false)};
 if(loading)return <article className="feature-panel schedule-panel"><div className="booking-empty">Carregando horários...</div></article>;
 return <div className="schedule-stack"><article className="feature-panel schedule-panel"><div className="schedule-heading"><div><div className="feature-icon">H</div><h2>Horário de funcionamento</h2><p>Defina quando a barbearia recebe agendamentos.</p></div></div><div className="schedule-list">{shopHours.map((r,i)=><div className="schedule-row" key={i}><label className="schedule-day"><input type="checkbox" checked={r.active} onChange={e=>updateShop(i,"active",e.target.checked)}/><strong>{days[i]}</strong></label><label>Abre<input type="time" value={r.open_time} disabled={!r.active} onChange={e=>updateShop(i,"open_time",e.target.value)}/></label><label>Fecha<input type="time" value={r.close_time} disabled={!r.active} onChange={e=>updateShop(i,"close_time",e.target.value)}/></label><label>Intervalo início<input type="time" value={r.break_start} disabled={!r.active} onChange={e=>updateShop(i,"break_start",e.target.value)}/></label><label>Intervalo fim<input type="time" value={r.break_end} disabled={!r.active} onChange={e=>updateShop(i,"break_end",e.target.value)}/></label></div>)}</div><button className="schedule-save" type="button" disabled={saving} onClick={saveShop}>{saving?"Salvando...":"Salvar funcionamento"}</button></article><article className="feature-panel schedule-panel"><div className="schedule-heading"><div><div className="feature-icon">B</div><h2>Disponibilidade dos barbeiros</h2><p>O cliente só verá horários em que o barbeiro estiver disponível.</p></div><select value={selectedBarber} onChange={e=>setSelectedBarber(e.target.value)} disabled={!barbers.length}><option value="">Selecione um barbeiro</option>{barbers.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></div>{!barbers.length?<div className="schedule-empty">Cadastre um barbeiro ativo no módulo Equipe para configurar a disponibilidade.</div>:<><div className="schedule-list">{barberHours.map((r,i)=><div className="schedule-row barber-schedule-row" key={i}><label className="schedule-day"><input type="checkbox" checked={r.active} onChange={e=>updateBarber(i,"active",e.target.checked)}/><strong>{days[i]}</strong></label><label>Início<input type="time" value={r.start_time} disabled={!r.active} onChange={e=>updateBarber(i,"start_time",e.target.value)}/></label><label>Fim<input type="time" value={r.end_time} disabled={!r.active} onChange={e=>updateBarber(i,"end_time",e.target.value)}/></label></div>)}</div><button className="schedule-save" type="button" disabled={saving} onClick={saveBarber}>{saving?"Salvando...":"Salvar disponibilidade"}</button></>}{message&&<div className="service-message success">{message}</div>}{error&&<div className="service-message error">{error}</div>}</article></div>;
}