"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase";
import "../login/cliente.css";

type Appointment={id:string;barbershop_id:string;appointment_date:string;appointment_time:string;barber_name:string;services:string[];status:string};
function formatDate(v:string){const [y,m,d]=v.split("-").map(Number);return new Date(y,m-1,d).toLocaleDateString("pt-BR",{weekday:"short",day:"2-digit",month:"2-digit",year:"numeric"})}
function isUpcoming(a:Appointment){const dateTime=new Date(`${a.appointment_date}T${a.appointment_time}`);return dateTime>=new Date()&&!['cancelled','canceled','completed'].includes((a.status||'').toLowerCase())}
export default function AgendamentosCliente(){const router=useRouter();const [items,setItems]=useState<Appointment[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");useEffect(()=>{(async()=>{const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/cliente/login");return}const {data,error:e}=await supabase.from("appointments").select("id,barbershop_id,appointment_date,appointment_time,barber_name,services,status").eq("client_id",user.id).order("appointment_date",{ascending:true}).order("appointment_time",{ascending:true});if(e){setError("Não foi possível carregar seus agendamentos.");setLoading(false);return}setItems((data||[]) as Appointment[]);setLoading(false)})()},[router]);const upcoming=items.filter(isUpcoming);return <main className="customer-shell"><header className="customer-header"><div className="customer-brand">Barba<span>10</span></div><div className="customer-shop">Agendamentos</div></header><section className="customer-content"><div className="customer-card"><span className="customer-kicker">ÁREA DO CLIENTE</span><h1>Agendamentos</h1><p>Seus próximos horários confirmados.</p>{loading?<div className="customer-message">Carregando...</div>:error?<div className="customer-error">{error}</div>:upcoming.length===0?<div className="customer-message">Você não tem próximos agendamentos.</div>:<div style={{display:"grid",gap:10}}>{upcoming.map(a=><div key={a.id} style={{padding:15,border:"1px solid #29292d",borderRadius:13,background:"#19191d"}}><strong>{formatDate(a.appointment_date)} às {a.appointment_time.slice(0,5)}</strong><p style={{margin:"8px 0 0",color:"#aaa"}}>{a.barber_name} • {(a.services||[]).join(", ")}</p></div>)}</div>}<button className="customer-back" onClick={()=>router.push("/agendamento")}>Novo agendamento</button></div></section></main>}
